name: Sync

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build
      run: |
        npm install
        npm run build --if-present
      env:
        CI: true
    - name: Sync to Gitee
      uses: wearerequired/git-mirror-action@master
      env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
      with:
          source-repo: "git@github.com:doocs/md.git"
          destination-repo: "git@gitee.com:Doocs/md.git"

    - name: Build Gitee Pages
      uses: yanglbme/gitee-pages-action@master
      with:
          gitee-username: yanglbme
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: doocs/md
